version: "3.0"

services: 
    bot:
        image: ghcr.io/djnotes/madelineproto-container:latest
    

        volumes:
            # - ./session:/app/session
            - .:/app

        
        # entrypoint: 
        #     - php
        #     - /app/bot.php
        # command: 
        #    - djnotes

        stdin_open: true
        tty: true


