name: Docker Hub Image CI

on: [push]
env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: powergame
  IMAGE_NAME: madelineproto-image

jobs:
  DockerHub-Build-Push: 
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code 
        uses: actions/checkout@v2
      - run: echo "${{ github.repository }} cloned to the runner."
      
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type:ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      # - name: Log In to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ env.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PAT }}

      # - name: Build and Push to Docker Hub
      #   id: build-push
      #   uses: docker/build-push-action@v3
      #   with: 
      #     file: ./Containerfile
      #     push: true
      #     tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      - name: Buildah Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
      
      - name: Push to registry
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Echo Outputs
        run: |
          echo "Image built and pushed."
          # echo "Image ID: ${{ steps.build-push.outputs.imageid }}"
          # echo "Image Digetst: ${{ steps.build-push.ouputs.digest }}"
          # echo "Image metadata: ${{ steps.build-push.outputs.metadata }}"
          echo "Image labels: ${{ steps.meta.outputs.labels }}"

      


