name: Docker Hub Image CI

on: [push]

jobs:
  DockerHub-Build-Push: 
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code 
        uses: actions/checkout@v2
      - run: echo "${{ github.repository }} cloned to the runner."
      
      - name: Log In to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/madelineproto:latest

      


